
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Address
{

    public int codeAddress { get; set; }

    public string entityGUID { get; set; }

    public string street { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public string contactemail1 { get; set; }

    public string contactemail2 { get; set; }

    public Nullable<int> addressType { get; set; }

    public string state { get; set; }

}

}
