
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class ciudades
{

    public int id_ciudad { get; set; }

    public int id_estado { get; set; }

    public string ciudad { get; set; }

    public byte capital { get; set; }



    public virtual estados estados { get; set; }

}

}
