
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class consignatario
{

    public int idConsignatario { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string AccessPassword { get; set; }

    public string apellido { get; set; }

    public string telefono { get; set; }

    public string sexo { get; set; }

    public string cedula { get; set; }

    public string sector { get; set; }

    public Nullable<bool> isEmailVerified { get; set; }

    public Nullable<System.Guid> ActivationCode { get; set; }

    public System.DateTime fecha_creacion { get; set; }

    public Nullable<bool> infoInMagaya { get; set; }



    public virtual consignatario consignatario1 { get; set; }

    public virtual consignatario consignatario2 { get; set; }

}

}
