
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class CustomLog
{

    public int LogId { get; set; }

    public string Message { get; set; }

    public string LogType { get; set; }

    public string RequestUri { get; set; }

    public string RequestedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

}

}
