
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Entities
{

    public int entityCode { get; set; }

    public string GUID { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string Email { get; set; }

    public string AccountNumber { get; set; }

    public string ParentName { get; set; }

    public Nullable<bool> IsPrepaid { get; set; }

    public string MobilePhone { get; set; }

    public string EntityID { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public string ExporterID { get; set; }

    public string ExporterIDType { get; set; }

}

}
