
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Events
{

    public Nullable<System.DateTime> Date { get; set; }

    public string WRCode { get; set; }

    public int EventCode { get; set; }

    public string EventDefinitionName { get; set; }

    public Nullable<bool> IncludeInTracking { get; set; }

    public string OwnerType { get; set; }

    public string OwnerNumber { get; set; }

    public string OwnerGUID { get; set; }

}

}
