
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class EventDefinition
{

    public int id { get; set; }

    public string Name { get; set; }

    public bool IncludeInTracking { get; set; }

    public string OwnerNumber { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

}

}
