
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class PasswordRecovery
{

    public int id { get; set; }

    public string Email { get; set; }

    public Nullable<System.Guid> RecoveryKey { get; set; }

    public Nullable<System.DateTime> date_to { get; set; }

    public Nullable<bool> IsRecovered { get; set; }

}

}
