
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentTerms
{

    public int codePaymentTerms { get; set; }

    public string Description { get; set; }

    public Nullable<int> NetDueDays { get; set; }

    public Nullable<decimal> DiscountPercentage { get; set; }

    public Nullable<int> DiscountPaidDays { get; set; }

    public string clientGUID { get; set; }

}

}
