
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class WareHouseReceiptsItems
{

    public int codeWHItem { get; set; }

    public string WarehouseReceiptGUID { get; set; }

    public string GUID { get; set; }

    public string Type { get; set; }

    public Nullable<int> Version { get; set; }

    public string Status { get; set; }

    public Nullable<int> Pieces { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> PieceQuantity { get; set; }

    public Nullable<bool> IsSummarized { get; set; }

    public string TrackingNumber { get; set; }

    public string PackageName { get; set; }

    public Nullable<int> WHRItemID { get; set; }

    public Nullable<double> Length { get; set; }

    public Nullable<double> Height { get; set; }

    public Nullable<double> Width { get; set; }

    public Nullable<double> Weight { get; set; }

    public Nullable<bool> ContainedPiecesWeightIncluded { get; set; }

    public Nullable<double> Volume { get; set; }

    public Nullable<double> VolumeWeight { get; set; }

    public Nullable<double> PieceWeight { get; set; }

    public Nullable<double> PieceVolume { get; set; }

    public string PackageType { get; set; }

    public string InShipmentGUID { get; set; }

    public Nullable<bool> IncludeInSED { get; set; }

    public Nullable<bool> IsContainer { get; set; }

    public string OutMasterWayBillNumber { get; set; }

    public string OutHouseWayBillNumber { get; set; }

    public string InMasterWayBillNumber { get; set; }

    public string InHouseWayBillNumber { get; set; }

    public Nullable<System.DateTime> ArrivalDate { get; set; }

    public string WarehouseReceiptNumber { get; set; }

    public Nullable<int> OrderIndex { get; set; }

    public Nullable<bool> IsPallet { get; set; }

    public Nullable<bool> IsOverstock { get; set; }

    public Nullable<bool> NotLoaded { get; set; }

    public Nullable<bool> InTask { get; set; }

    public Nullable<System.DateTime> EntryDate { get; set; }

    public string OutShipmentGUID { get; set; }

    public string Notes { get; set; }

    public string LastReceptionNetworkID { get; set; }

    public string ShipmentType { get; set; }

    public string OutDate { get; set; }

}

}
