
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class WareHouseAttach
{

    public int Identifier { get; set; }

    public string OwnerGUID { get; set; }

    public string OwnerType { get; set; }

    public Nullable<int> Size { get; set; }

    public Nullable<bool> IsInternal { get; set; }

    public Nullable<bool> IsImage { get; set; }

    public string Extension { get; set; }

    public string Name { get; set; }

    public byte[] Imagen { get; set; }

    public int Id { get; set; }

}

}
